### ISSUE TITLE
出错了，请稍后再试；如果您是管理员，请检查日志。

### ISSUE THREAD

**Issue by DevCoz** [hobk/chatgpt-telebot#11]
出错了，之后需要重新进入vps 启动node index.js，不能自己重启吗？

错误信息：
Error: ChatGPTError: ChatGPT error 429: {
  "error": {
    "message": "The server had an error while processing your request. Sorry about that!",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

    at file:///root/chatgpt-telebot/node_modules/chatgpt/build/index.js:202:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 429,
  statusText: 'Too Many Requests',
  [cause]: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 429,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Too Many Requests',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

ChatGPTError: ChatGPT error 429: {
  "error": {
    "message": "The server had an error while processing your request. Sorry about that!",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

    at file:///root/chatgpt-telebot/node_modules/chatgpt/build/index.js:202:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 429,
  statusText: 'Too Many Requests',
  [cause]: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 429,
      timingInfo: {
        startTime: 616692.6532439999,
        redirectStartTime: 0,
        redirectEndTime: 0,
        postRedirectStartTime: 616692.6532439999,
        finalServiceWorkerStartTime: 0,
        finalNetworkResponseStartTime: 0,
        finalNetworkRequestStartTime: 0,
        endTime: 0,
        encodedBodySize: 0,
        decodedBodySize: 0,
        finalConnectionTimingInfo: null
      },
      cacheState: '',
      statusText: 'Too Many Requests',
      headersList: HeadersList {
        cookies: null,
        [Symbol(headers map)]: Map(11) {
          'date' => { name: 'Date', value: 'Thu, 09 Feb 2023 08:54:49 GMT' },
          'content-type' => { name: 'Content-Type', value: 'application/json' },
          'content-length' => { name: 'Content-Length', value: '176' },
          'connection' => { name: 'Connection', value: 'keep-alive' },
          'access-control-allow-origin' => { name: 'Access-Control-Allow-Origin', value: '*' },
          'openai-model' => { name: 'Openai-Model', value: 'text-davinci-003' },
          'openai-organization' => {
            name: 'Openai-Organization',
            value: 'user-pkn4yjuxkljmayvbfvrktlts'
          },
          'openai-processing-ms' => { name: 'Openai-Processing-Ms', value: '2749' },
          'openai-version' => { name: 'Openai-Version', value: '2020-10-01' },
          'strict-transport-security' => {
            name: 'Strict-Transport-Security',
            value: 'max-age=15724800; includeSubDomains'
          },
          'x-request-id' => {
            name: 'X-Request-Id',
            value: '7270b8658ace6472e495ca7fb03e4d5c'
          }
        },
        [Symbol(headers map sorted)]: null
      },
      urlList: [
        <ref *1> URL {
          [Symbol(context)]: URLContext {
            flags: 400,
            scheme: 'https:',
            username: '',
            password: '',
            host: 'api.openai.com',
            port: null,
            path: [Array],
            query: null,
            fragment: null
          },
          [Symbol(query)]: URLSearchParams {
            [Symbol(query)]: [],
            [Symbol(context)]: [Circular *1]
          }
        }
      ],
      body: {
        stream: ReadableStream {
          [Symbol(kType)]: 'ReadableStream',
          [Symbol(kState)]: {
            disturbed: true,
            reader: [ReadableStreamDefaultReader],
            state: 'closed',
            storedError: undefined,
            stream: undefined,
            transfer: [Object],
            controller: [ReadableStreamDefaultController]
          },
          [Symbol(nodejs.webstream.isClosedPromise)]: {
            promise: [Promise],
            resolve: [Function (anonymous)],
            reject: [Function (anonymous)]
          }
        }
      }
    },
    [Symbol(headers)]: Headers {
      [Symbol(headers list)]: HeadersList {
        cookies: null,
        [Symbol(headers map)]: Map(11) {
          'date' => { name: 'Date', value: 'Thu, 09 Feb 2023 08:54:49 GMT' },
          'content-type' => { name: 'Content-Type', value: 'application/json' },
          'content-length' => { name: 'Content-Length', value: '176' },
          'connection' => { name: 'Connection', value: 'keep-alive' },
          'access-control-allow-origin' => { name: 'Access-Control-Allow-Origin', value: '*' },
          'openai-model' => { name: 'Openai-Model', value: 'text-davinci-003' },
          'openai-organization' => {
            name: 'Openai-Organization',
            value: 'user-pkn4yjuxkljmayvbfvrktlts'
          },
          'openai-processing-ms' => { name: 'Openai-Processing-Ms', value: '2749' },
          'openai-version' => { name: 'Openai-Version', value: '2020-10-01' },
          'strict-transport-security' => {
            name: 'Strict-Transport-Security',
            value: 'max-age=15724800; includeSubDomains'
          },
          'x-request-id' => {
            name: 'X-Request-Id',
            value: '7270b8658ace6472e495ca7fb03e4d5c'
          }
        },
        [Symbol(headers map sorted)]: null
      },
      [Symbol(guard)]: 'immutable',
      [Symbol(realm)]: null
    }
  }
}

Node.js v19.6.0

**Comment by hobk** [comment]
错误是因为statusCode: 429, statusText: 'Too Many Requests',
建议使用pm2 start index.js （先安装 npm i pm2 -g）

**Comment by DevCoz** [comment]
好的，谢谢。
